name: AIO

on:
    push:
        branches: [main]
        paths:
            - "aio/**"

    workflow_dispatch:

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

env:
    DOCKER_REGISTRY: docker.io
    DOCKER_IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/aio

jobs:
    build-and-deploy:
        name: Build and Deploy
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Login to Docker Hub Registry
              uses: docker/login-action@v3
              with:
                  registry: ${{ env.DOCKER_REGISTRY }}
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build and Push to Docker Hub
              uses: docker/build-push-action@v5
              with:
                  context: ./aio
                  file: ./aio/Dockerfile
                  platforms: linux/amd64
                  push: true
                  tags: ${{ env.DOCKER_IMAGE_NAME }}:latest
