name: AIO

on:
    push:
        branches: [main]
        paths:
            - "aio/**"

    workflow_dispatch:

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository }}

jobs:
    build-and-deploy:
        name: Build and Deploy
        runs-on: debian-latest

        steps:
            - uses: actions/checkout@v4

            - name: Setup Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to Registry
              uses: docker/login-action@v3
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and Push Image
              uses: docker/build-push-action@v5
              with:
                  context: ./aio
                  file: ./aio/Dockerfile
                  platforms: linux/amd64
                  push: true
                  tags: ghcr.io/wdhdev/yolks:aio
