name: PSL NGINX

on:
    push:
        branches: [main]
        paths:
            - "psl-nginx/**"

    workflow_dispatch:

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Build Image
              uses: docker/build-push-action@v6
              with:
                  context: ./psl-nginx
                  file: ./psl-nginx/Dockerfile
                  platforms: linux/amd64
                  push: false
