name: PSL NGINX

on:
    push:
        branches: [main]
        paths:
            - "psl-nginx/**"

    workflow_dispatch:

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

env:
    DOCKER_IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/psl-nginx
    DOCKER_REGISTRY: docker.io

jobs:
    build-and-deploy:
        name: Build and Deploy
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Login to ${{ env.DOCKER_REGISTRY }}
              uses: docker/login-action@v3
              with:
                  registry: ${{ env.DOCKER_REGISTRY }}
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build and Push Image
              uses: docker/build-push-action@v6
              with:
                  context: ./psl-nginx
                  file: ./psl-nginx/Dockerfile
                  platforms: linux/amd64
                  push: true
                  tags: |
                      ${{ env.DOCKER_IMAGE_NAME }}:latest
